apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  kubeConfig: "/mnt/d/mlops/kubeconfig/kubeconfig"
  master: ""
modules:
  cloudHub:
    enable: true
    address: "0.0.0.0"
    port: 10000
    quicPort: 10002
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
    tlsCAFile: "/etc/kubeedge/ca/rootCA.crt"
    tlsCertFile: "/etc/kubeedge/certs/edge.crt"
    tlsPrivateKeyFile: "/etc/kubeedge/certs/edge.key"
  edgeController:
    enable: true
    kube:
      kubeConfig: "/mnt/d/mlops/kubeconfig/kubeconfig"
  deviceController:
    enable: true
    kube:
      master: ""
      kubeConfig: "/mnt/d/mlops/kubeconfig/kubeconfig"
  syncController:
    enable: true
    kube:
      kubeConfig: "/mnt/d/mlops/kubeconfig/kubeconfig"
